services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: f2fef0677fdb1b892526d4326d34265f0aae7c4bb36c4731a9e7451126b10c08
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    container_name: redis-db
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 8807eaf911bbc47208549f7e610e99f64ade30b79e8aea4717f8d35c169d1f0f
    volumes:
      - redis:/data
volumes:
  pgdata:
  redis:
    driver: local